services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    image: insite-frontend:dev
    ports:
      - 3000:3000
    environment:
      - API_URL=http://backend:3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: insite-backend:dev
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - database

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db

volumes:
  frontend_node_modules:
  frontend_next:
  backend_node_modules:
